### ISSUE TITLE
Stazene produkty nemaji nazev uploadnuteho zipu

### ISSUE THREAD

**Issue by rojcyk** [rojcyk/rojcyk-app#11]
Kdyz stahnes nejaky produkt, tak misto nazvu (toho ktery jsem nahral), ma v nazvu asi token? Chtelo by to by si ten fajl uchovaval nazev.

**Comment by hromadkom** [comment]
done

**Comment by rojcyk** [comment]
jeste to chce vychytat tuhle drobnost! :) ![screen shot 2017-02-15 at 20 05 19](https://cloud.githubusercontent.com/assets/1080609/22990726/62804ed8-f3ba-11e6-8066-769ad7b7150a.png)

**Comment by hromadkom** [comment]
jeden ten pridany string tam asi bude muset zustat, jinak se to bude prepisovat a nebude fungovat historie bude to vypadat takhle `blueprint-a540a7.sketch.zip` - pokud by to byl velky problem, tak bychom to nejak vyresili

**Comment by rojcyk** [comment]
hele to nebude problem, ja je budu v nazvuu verzovat .. .tzn. blueprint-1v atd. :)

**Comment by hromadkom** [comment]
okey ... tak ja ten radom string vyhodim
