### ISSUE TITLE
Napojeni usera na mailjet mailing list

### ISSUE THREAD

**Issue by rojcyk** [rojcyk/rojcyk-app#12]
- V momente kdy potvrdi svuj ucet (tzn. stahne nejaky produkt skrze email), tak ho pridame do mailing listu na mailetu
- Pokud si potom v settings vypne mailing list, tak se odstrani z mailing listu na mailjetu
- ^^ to stejne plati pro zapnuti

**Comment by rojcyk** [comment]
TOhle zatim nech tak, potrebuju si poradne jeste projit ty sluzby a mrknout na to co poskytuji.

**Comment by hromadkom** [comment]
Mam teda tady pocitat mailchimp?

**Comment by rojcyk** [comment]
Jop, jak budes cokoliv potrebovat tak slack

**Comment by hromadkom** [comment]
done

**Comment by rojcyk** [comment]
Hele, kdyz projdu to cele flow, tzn. stahnu ten product skrze link v emailu, tak se uzik neprida do mailing listu.

**Comment by rojcyk** [comment]
A tak jsem to fixnul 💪
