### ISSUE TITLE
Uprava signup flow

### ISSUE THREAD

**Issue by rojcyk** [rojcyk/rojcyk-app#17]
Hele uz to funguje temer odkonale, az na jeden malicky detail ... ktery jsem totalne prehledl :( Udelame to tak, ze aktualni thank you page nebude obsahovat ten formular na heslo ale jenom informaci o tom ze se ma jit mrknout do emailu. Jak ti ale takovy email prijde, a ty potvrdis adresu (stahnes produkt), tak az pak se dostanes na stranku kde si nastavis heslo. Tohle chybi celemu tomu flow k dokonalosti :)

**Comment by hromadkom** [comment]
done
