### ISSUE TITLE
Do emailu se neposila nazev produktu

### ISSUE THREAD

**Issue by rojcyk** [rojcyk/rojcyk-app#29]
A chodi email jen jako "Download link for ..."

**Comment by hromadkom** [comment]
![snimek obrazovky 2017-03-15 v 17 00 13](https://cloud.githubusercontent.com/assets/1903652/23957928/e465c4f4-09a0-11e7-8a2d-dc15570cbef8.png)

**Comment by hromadkom** [comment]
Chodi to i s nazvem produktu - nezkracuje ti to email klient?

**Comment by rojcyk** [comment]
Nn, mrkni na detailu toho email u... jde to videt i tady z toho screenshotu ... "Download link for" a pak "Download". Ma tam byt "Download link for Blueprint" a pak "Download Blueprint"

**Comment by hromadkom** [comment]
FIXED: problem byl v serializaci te hash s produktem
