### ISSUE TITLE
Cena produktu neumi desetiny a setiny

### ISSUE THREAD

**Issue by rojcyk** [rojcyk/rojcyk-app#36]
Takze nenastavim popularni cenovku 9,99

**Comment by hromadkom** [comment]
az deploynes zmeny tak dej `heroku run rake db:reseed`

**Comment by rojcyk** [comment]
Je to tam, jen jedna vec. Mam v heroku nastaveny auto deploy, takze kdyz to hazis do masteru, tak tyhle veci udelej prosimte rovnou.

**Comment by rojcyk** [comment]
Jinak diky, fici!
