### ISSUE TITLE
Signu Up / Download flow

### ISSUE THREAD

**Issue by rojcyk** [rojcyk/rojcyk-app#9]
V momente, kdy uzik klikne na download link, dostane se na thank you stranku, tak by bylo fajn, kdyby tam byl formular, do ktereho kdyz napise heslo, tak se mu ulozi k profilu. A cele to kolecko se pak uzavre :)

**Comment by hromadkom** [comment]
done

**Comment by rojcyk** [comment]
Hele, muze tohle byt primo na te strance? Misto presmerovavani do settings?

**Comment by hromadkom** [comment]
Pro rychlost jsem tam pouzil ten samej form co v settings ... kdyby to tam neslo nejak nastylovat, tak to kuchnem :-D
